### ISSUE TITLE
Completion does not work any more with company-mode

### ISSUE THREAD

**Issue by D4N** [krzysztof-magosa/company-ansible#2]
I have used this package for quite a while and it has proven to be very useful, thanks for creating it!

However recently (unfortunately I do not know when exactly), it stopped working with company-mode. When I start editing an ansible file, company-mode complains all the time with:
```
Company: An error occurred in auto-begin
Company: backend company-ansible error "Wrong type argument: sequencep, get_status" with args (candidates state)
```
I am using company-mode from melpa, which at this point is version 0.9.6.

**Comment by foreverqihe** [comment]
same for me. It happens after updating to 0.9.6
